Favorites.allow({
  insert: function(userId, doc) {
    return doc.owner === userId;
  },
  remove: function(userId, doc) {
    return doc.owner === userId;
  }
});

// ---
// generated by coffee-script 1.9.2